### ISSUE TITLE
rx.mini.EventDisposer is not a constructor

### ISSUE THREAD

**Issue by kolserdav** [shinyoshiaki/werift-webrtc#305]
Looks like this refactoring broke something https://github.com/shinyoshiaki/werift-webrtc/commit/d3300bf0b05c2714ebc74acbc36b1bf41131ca97
```sh
[0] [1] 07:50:32  error  unhandledRejection  TypeError: rx_mini_1.EventDisposer is not a constructor
[0] [1]     at new WebmFactory (/home/kol/Projects/werift-sfu-react/node_modules/werift/lib/webrtc/src/nonstandard/recorder/writer/webm.js:13:30)
[0] [1]     at /home/kol/Projects/werift-sfu-react/node_modules/werift/lib/webrtc/src/nonstandard/recorder/index.js:14:28
[0] [1]     at new MediaRecorder (/home/kol/Projects/werift-sfu-react/node_modules/werift/lib/webrtc/src/nonstandard/recorder/index.js:18:11)
[0] [1]     at RecordVideo.startStreamRecord (/home/kol/Projects/werift-sfu-react/packages/server/dist/addons/recordVideo.js:182:56)
[0] [1]     at /home/kol/Projects/werift-sfu-react/packages/server/dist/addons/recordVideo.js:225:26
[0] [1]     at Array.forEach (<anonymous>)
[0] [1]     at RecordVideo.handleVideoRecord (/home/kol/Projects/werift-sfu-react/packages/server/dist/addons/recordVideo.js:221:49)
[0] [1]     at WebSocket.<anonymous> (/home/kol/Projects/werift-sfu-react/packages/server/dist/main.js:198:33)
[0] [1]     at WebSocket.emit (node:events:527:28)
[0] [1]     at Receiver.receiverOnMessage (/home/kol/Projects/werift-sfu-react/node_modules/ws/lib/websocket.js:1178:20)  
[0] [1] 
```

**Comment by shinyoshiaki** [comment]
Remove node_modules and package-lock.json and reinstall
